# Server Configuration:

whitelist: false
# A whilelist is essentially this; Nobody can join EXCEPT those on the whitelist;

blacklist: false
# A Blacklist is essentially this; Everybody can join EXCEPT those on the blacklist;

whitelistlist:
- []

blacklistlist:
- []
# Is Password Enabled, if false, players wont need to use a password to join
IsPasswordEnabled: true
Password: "test"

DebugEnabled: true
# Default = False, While true, it will print out all raw data

# Max Players is HOW Many players can join. once that amount of players has achieved, the players attepting to join will be kicked with the message "This Server is Popular, check back later"
maxplayers: 10

# due to limitations, max Players cannot be above 255
